#!/usr/bin/ruby

IRB.conf[:AUTO_INDENT] = true
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"
IRB.conf[:PROMPT_MODE] = :SIMPLE
IRB.conf[:SAVE_HISTORY] = 1000

class Object
  def local_methods(obj =  self)
    (obj.methods - obj.superclass.instance_methods).sort
  end
end 

def r
  reload!
end
