" Make sure we are not running in compatible mode
if &compatible
  set nocompatible
endif

" Install Vim-plug if it's not already there
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Vim-plug
call plug#begin()

Plug 'arcticicestudio/nord-vim'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" Move the .viminfo file into .vim
set viminfo+=n~/.vim/viminfo

filetype plugin indent on " File type detection
syntax on " Syntax highlighting

set background=dark                     " Dark colors
set backspace=indent,eol,start          " Make backspace work correctly
set hlsearch                            " Highlight search results
set ignorecase                          " Case insensitive searching
set incsearch                           " Incremental search highlighting
set number                              " Turn on line numbers
set ruler                               " Show cursor position
set showcmd                             " Show the command
set smartcase                           " Smart case matching when searching
set termguicolors                       " Use 24 bit color

" Setup our tabs and spaces
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Set our colorscheme
colorscheme nord

" Change cursor on insert and normal modes
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Keymappings for FZF
nnoremap <silent> <C-p> :Files<CR>
"nnoremap <silent> <C-f> :Rg<CR>

" Airline config
let g:airline_powerline_fonts = 1
