# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Extend the timeout
command_timeout = 10000

[aws]
disabled = true

[directory]
truncate_to_repo = false
truncation_symbol = '../'

[kubernetes]
disabled = true
