alias bex="bundle exec"
alias c="clear"
alias cd..="cd .."
alias cp="cp -i"
alias cz="chezmoi"
alias la="ls -al"
alias ll="ls -l"
alias ls="lsd --ignore-glob=$'Icon\r'"
alias lt="ls --tree"
alias k="kubectl"
alias mv="mv -i"
alias rm="rm -i"
alias tree="lt"
alias wget="wget --hsts-file=\"${XDG_DATA_HOME}/wget-hsts\""
alias vim="nvim"
