require('plugins.packer')
require('plugins.lspconfig')
require('plugins.lualine')
require('plugins.treesitter')
require('zspoelstra.options')
require('zspoelstra.keymaps')
require('zspoelstra.autocmd')
